# Extensão [Rest Client] necessária

###GET Relatórios
GET http://localhost:3000/relatorios HTTP/1.1

###CREATE
POST    http://localhost:3000/relatorios  HTTP/1.1
content-type: application/json

{
    "alunoId": 1,
    "alunoEmail": "AnaJulia@gmail.com",
    "data": "12/02/2022",
    "peso": 58.00, 
    "altura": 1.68,
    "imc": 20.00,
    "gordura": ""
}


PUT  http://localhost:3000/relatorios/ HTTP/1.1
content-type: application/json

{
    "alunoName": "Ana Júlia",
    "alunoEmail": "AnaJulia@gmail.com",
    "data": "12/02/2022",
    "peso": 58.00, 
    "altura": 1.68,
    "imc": 20.00,
    "gordura": "",
}
