# Extensão [Rest Client] necessária

###GET 
GET http://localhost:3000/users HTTP/1.1

###CREATE
POST  http://localhost:3000/register HTTP/1.1
content-type: application/json

{
    "name": "Ana",
    "email": "Ana@gmail.com",
    "password": "12345",
    "rule": "admin", 
    "endereco": "rua morteiro, 351",
    "nascimento": "14/12/1999",
    "desde": "30/04/2022"
}

###LOGIN
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "Ana@gmail.com",
    "password": "12345"
}